import "./globals.css";
import { Roboto } from "next/font/google";
import store, { Provider } from "@/features/store";
import { ThemeProvider } from "@/components/theme/ThemeChange";

// const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "AstroTitans",
  description: "Generated by Redwan Rakib",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider store={store}>
          <ThemeProvider attribute="class">{children}</ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
